# Generated by Django 2.1 on 2019-03-05 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter_clone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
