#notifications:
#  slack:
#    rooms:
#      - soen341corp:S6vnts4jdYRFyzVJHHNGvDSd#twitterapp

sudo: required
dist: "trusty"
language: python
python:
        - "3.6.7"

addons:
        apt:
                packages:
                        - "python3"
                        - "python3-pip"

before_install:
        - sudo apt-get -y install python3-pip python-dev
        - sudo pip3 install -U Django==2.1.7

          #env:
        #    - DJANGO_VERSION=2.1.5
        #    - DJANGO_VERSION=2.1.7
    
      #install:
        #    - pip3 install -q Django==$DJANGO_VERSION

before_script:
    - source ENV/bin/activate
      #    - apt install python3-pip
      #    - pip3 install Django==$DJANGO_VERSION
    - cd twitter_clone/

script:
    - python3 manage.py runserver
