#notifications:
#  slack:
#    rooms:
#      - soen341corp:S6vnts4jdYRFyzVJHHNGvDSd#twitterapp

language: python
python:
        - "3.6.7"
env:
        - DJANGO=2.1.7 DB=postresql
install:
        - pip3 install -r requirements.txt
before_script:
        - source ENV/bin/activate
        - cd twitter_clone
script:
        - python3 manage.py test
